// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltbnuihljxyjqjtwrhtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Ym51aWhsanh5anFqdHdyaHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDEwMzcsImV4cCI6MjA2MzIxNzAzN30.fHsxbUvUCh2ttEbN-np-u2_8vnb8ExbEHRwPwM7V5QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);