// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltbnuihljxyjqjtwrhtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Ym51aWhsanh5anFqdHdyaHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDEwMzcsImV4cCI6MjA2MzIxNzAzN30.fHsxbUvUCh2ttEbN-np-u2_8vnb8ExbEHRwPwM7V5QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with proper configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        persistSession: true,
        autoRefreshToken: true,
    },
    db: {
        schema: 'public'
    },
    global: {
        headers: {
            'Content-Type': 'application/json',
            'apikey': SUPABASE_PUBLISHABLE_KEY
        }
    }
});

// Helper function to handle Supabase errors
export const handleSupabaseError = (error: any) => {
    console.error('Supabase Error:', error);
    if (error.code === 'PGRST301') {
        throw new Error('Authentication required');
    }
    if (error.code === 'PGRST404') {
        throw new Error('Resource not found');
    }
    throw new Error(error.message || 'An error occurred with the database');
};